### ISSUE TITLE
Module4 (Front-End Dev): not working in Internet Explorer 11

### ISSUE THREAD

**Issue by hhubik** [Microsoft-Build-2016/CodeLabs-WebDev#24]
Great tutorial! Thank you!.  While going through Module 4 (Front-end dev), I notice that the demos don't work (most of the time) in IE 11 (Windows 10 x64) even though they work fine in Mozilla Firefox. 
`HTML1300: Navigation occurred.
File: localhost:55804
EXCEPTION: SyntaxError: Expected ';'
   EXCEPTION: SyntaxError: Expected ';'

EXCEPTION: Error: Uncaught (in promise): SyntaxError: Expected ';'
   EXCEPTION: Error: Uncaught (in promise): SyntaxError: Expected ';'
   STACKTRACE:
   Error: Uncaught (in promise): SyntaxError: Expected ';'
   at resolvePromise (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:543:26)
   at Anonymous function (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:579:18)
   at ZoneDelegate.prototype.invokeTask (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:363:18)
   at onInvokeTask (http://localhost:55804/lib/npmlibs/angular2/angular2.js:2208:15)
   at ZoneDelegate.prototype.invokeTask (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:363:18)
   at Zone.prototype.runTask (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:263:22)
   at drainMicroTaskQueue (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:482:26)
   at invoke (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:434:22)

Unhandled Promise rejection: Expected ';' ; Zone: angular ; Task: Promise.then ; Value: SyntaxError: Expected ';'
   "Unhandled Promise rejection:"
   "Expected ';'"
   "; Zone:"
   "angular"
   "; Task:"
   "Promise.then"
   "; Value:"
   {
      [functions]: ,
      __proto__: { },
      description: "Expected ';'",
      message: "Expected ';'",
      name: "SyntaxError",
      number: -2146827284,
      stack: "SyntaxError: Expected ';'
   at evalExpression (http://localhost:55804/lib/npmlibs/angular2/angular2.js:459:5)
   at TemplateCompiler.prototype._createViewFactoryRuntime (http://localhost:55804/lib/npmlibs/angular2/angular2.js:25033:9)
   at Anonymous function (http://localhost:55804/lib/npmlibs/angular2/angular2.js:24987:13)
   at ZoneDelegate.prototype.invoke (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:330:14)
   at onInvoke (http://localhost:55804/lib/npmlibs/angular2/angular2.js:2216:15)
   at ZoneDelegate.prototype.invoke (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:330:14)
   at Zone.prototype.run (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:227:18)
   at Anonymous function (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:576:18)
   at ZoneDelegate.prototype.invokeTask (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:363:18)
   at onInvokeTask (http://localhost:55804/lib/npmlibs/angular2/angular2.js:22"
   }

Error: Uncaught (in promise): SyntaxError: Expected ';'
   {
      [functions]: ,
      __proto__: { },
      description: "Uncaught (in promise): SyntaxError: Expected ';'",
      message: "Uncaught (in promise): SyntaxError: Expected ';'",
      name: "Error",
      promise: { },
      rejection: { },
      stack: "Error: Uncaught (in promise): SyntaxError: Expected ';'
   at resolvePromise (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:543:26)
   at Anonymous function (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:579:18)
   at ZoneDelegate.prototype.invokeTask (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:363:18)
   at onInvokeTask (http://localhost:55804/lib/npmlibs/angular2/angular2.js:2208:15)
   at ZoneDelegate.prototype.invokeTask (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:363:18)
   at Zone.prototype.runTask (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:263:22)
   at drainMicroTaskQueue (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:482:26)
   at invoke (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:434:22)",
      task: { },
      zone: { }
   }

Unhandled Promise rejection: Expected ';' ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError: Expected ';'
   "Unhandled Promise rejection:"
   "Expected ';'"
   "; Zone:"
   "<root>"
   "; Task:"
   "Promise.then"
   "; Value:"
   {
      [functions]: ,
      __proto__: { },
      description: "Expected ';'",
      message: "Expected ';'",
      name: "SyntaxError",
      number: -2146827284,
      stack: "SyntaxError: Expected ';'
   at evalExpression (http://localhost:55804/lib/npmlibs/angular2/angular2.js:459:5)
   at TemplateCompiler.prototype._createViewFactoryRuntime (http://localhost:55804/lib/npmlibs/angular2/angular2.js:25033:9)
   at Anonymous function (http://localhost:55804/lib/npmlibs/angular2/angular2.js:24987:13)
   at ZoneDelegate.prototype.invoke (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:330:14)
   at onInvoke (http://localhost:55804/lib/npmlibs/angular2/angular2.js:2216:15)
   at ZoneDelegate.prototype.invoke (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:330:14)
   at Zone.prototype.run (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:227:18)
   at Anonymous function (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:576:18)
   at ZoneDelegate.prototype.invokeTask (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:363:18)
   at onInvokeTask (http://localhost:55804/lib/npmlibs/angular2/angular2.js:22"
   }

Error: Uncaught (in promise): SyntaxError: Expected ';'
   {
      [functions]: ,
      __proto__: { },
      description: "Uncaught (in promise): SyntaxError: Expected ';'",
      message: "Uncaught (in promise): SyntaxError: Expected ';'",
      name: "Error",
      promise: { },
      rejection: { },
      stack: "Error: Uncaught (in promise): SyntaxError: Expected ';'
   at resolvePromise (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:543:26)
   at resolvePromise (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:528:18)
   at Anonymous function (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:576:18)
   at ZoneDelegate.prototype.invokeTask (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:363:18)
   at Zone.prototype.runTask (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:263:22)
   at drainMicroTaskQueue (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:482:26)
   at invoke (http://localhost:55804/lib/npmlibs/angular2/angular2-polyfills.js:434:22)",
      task: { },
      zone: { }
   }`

**Comment by webprofusion-chrisc** [comment]
Try including:
 <script src="https://npmcdn.com/angular2/es6/dev/src/testing/shims_for_IE.js"></script>

index your index.html before other scripts.
